# Generated by Django 4.0.4 on 2022-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_skilltag_rename_name_skill_skill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Имя',
            field=models.CharField(default='dfg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='Отчество',
            field=models.CharField(default='dfg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='Фамилия',
            field=models.CharField(default='dfg', max_length=100),
            preserve_default=False,
        ),
    ]
