# Generated by Django 4.0.4 on 2022-05-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_имя_customuser_отчество_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Имя',
            new_name='patronymic',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Отчество',
            new_name='second_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Фамилия',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
