# Generated by Django 4.0.4 on 2022-05-20 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_second_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(related_name='skill_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='tag_name',
            field=models.CharField(max_length=50, verbose_name='категория'),
        ),
    ]
