# Generated by Django 4.0 on 2022-05-22 16:33

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
